# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e16828cb0def3d38c2b00ffbafed04a16b1041890152752a8611d75d673b9e079b4c7a655ca5761875266fe93ed18621f18a244730556a9f8974d496058ddc0b

test:
  secret_key_base: 9531d1fc7426d90b448a844882b14ef57832538c9e901c27367d64a6b05cbc905d1917d3d29fad27bcc4f716c270ea8064be75e2ac57bd9cfa36986db0dc1d8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
